# Use official Node.js image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source code
COPY . .

# Expose port
EXPOSE 5050

# Run the server
CMD ["node", "server.js"]
